const mongoose = require('mongoose');

const PurchaseRequestSchema = new mongoose.Schema({
    uuid: {
        type: String
    },
    requestNo: {
        type: String,
        required: [true, 'Please add request number']
    },
    generatedBy: {
        type: String,
        required: [true, 'Please add generated By'],
    },
    date: {
        type: Date,
        default: Date.now,
        required: [true, 'Please add date']
    },
    vendorId: {
        type: mongoose.Schema.ObjectId,
        ref: 'Vendor',
        required: [true, 'Please select Vendor']
    },
    status: {
        type: String,
        required: true
    },
    itemCode: {
        type: String,
        required: [true, 'Please add item code']
    },
    name: {
        type: String,
        required: [true, 'Please add item code']
    },
    description: {
        type: String,
        required: [true, 'Please add item code']
    },
    currentQty: {
        type: String,
        required: [true, 'Please add current qty']
    },
    reqQty: {
        type: String,
        required: [true, 'Please add req qty']
    },
    comments: {
        type: String,
        required: [true, 'Please add comments']
    },
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
});

module.exports = mongoose.model('PurchaseRequest', PurchaseRequestSchema);
